import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import StoreProvider from "@/redux/provider"; // wrap Redux once here
import ToasterProvider from "@/app/(components)/toaster-provider/ToasterProvider";
import ThemeWatcher from "@/app/(components)/theme-watcher/ThemeWatcher";
import MuiThemeProvider from "@/app/(components)/mui-theme-provider/MuiThemeProvider";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <Script
          id="no-flash"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var persistRoot = localStorage.getItem('persist:root');
                  if (persistRoot) {
                    var root = JSON.parse(persistRoot);
                    if (root.global) {
                      var global = JSON.parse(root.global);
                      if (global.isDarkMode) {
                        document.documentElement.classList.add('dark');
                      }
                    }
                  }
                } catch (e) {}
              })();
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <ThemeWatcher />
          <MuiThemeProvider>
            <ToasterProvider />
            {children}
          </MuiThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
